# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b21e5a71af32651a8136a90aba901d2c825536ecf3b48b1383e703cee0decdd756e0942940624d343ecc773932c3fa0e884a0a05fb90d5729d246a8eb76ae614

test:
  secret_key_base: cfaca3436fdb3f844721bc336a29a29a1c7597ec395670c9df0eee19ce7a566e067355c94ce461f26f20aa5449d8801a0dbcd66c3e4a1fce7edf9c86717c7037

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
